//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balance.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BalanceEntities : DbContext
    {
        public BalanceEntities()
            : base("name=BalanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceWithAdditionalField> DeviceWithAdditionalFields { get; set; }
        public virtual DbSet<AdditionalField> AdditionalFields { get; set; }
        public virtual DbSet<AdditionalFieldForDevice> AdditionalFieldForDevices { get; set; }
        public virtual DbSet<Kit> Kits { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<ModelOfDevice> ModelOfDevices { get; set; }
        public virtual DbSet<TypeOfDevice> TypeOfDevices { get; set; }
        public virtual DbSet<KitLoction> KitLoctions { get; set; }
    }
}
