//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balance.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceWithAdditionalField
    {
        public int IDDeviceWithAdditionalField { get; set; }
        public int DeviceID { get; set; }
        public int TypeOfDeviceID { get; set; }
        public int AdditionalFieldID { get; set; }
        public string Value { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual AdditionalFieldForDevice AdditionalFieldForDevice { get; set; }

        public override string ToString()
        {
            return Value;
        }
    }
}
