//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balance.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitLoction
    {
        public int KitID { get; set; }
        public int LocationID { get; set; }
        public string CompName { get; set; }
    
        public virtual Kit Kit { get; set; }
        public virtual Location Location { get; set; }

        public override string ToString()
        {
            return CompName;
        }
    }
}
